echo "We are trying this practical from linux EC2"
echo "We are from batch-33 and learning git/gihub"
echo "We are learning Branching"
echo "Git fork and git clone"
echo "My Name is Ranjit"
echo "My devops practice script"
echo "New Modification on 2 october 2026"
